#
# Hyper Operating System用クロス開発環境コンテナイメージ
#
# -*- coding:utf-8 mode: dockerfile-mode -*-
# Copyright (C) 1998-2022 by Project HOS
# http://sourceforge.jp/projects/hos/
#

# Ubuntu環境を使用
FROM ubuntu
# メインテナ名
LABEL maintainer="Project HOS"
# リポジトリと関連付ける
LABEL org.opencontainers.image.source https://github.com/takeharukato/crosstool-for-hos
# tzdataインストール時にタイムゾーンを聞かないようにする
ENV DEBIAN_FRONTEND=noninteractive
# ターゲットCPU
ENV TARGET_CPUS="__REPLACE_TARGET_CPUS__"
#
#事前準備
#
# 基本ディレクトリ
RUN mkdir -p /home/cross/mkcross/workdir ; \
    mkdir -p /home/cross/mkcross/patches/gdb ;

# クロスコンパイラ作成スクリプトをコピー
COPY scripts/mkcross-elf.sh /home/cross/mkcross
# QEmuのクロスでバッグ用パッチをコピー
COPY patches/gdb/gdb-8.3-qemu-x86-64.patch /home/cross/mkcross/patches/gdb
# コンパイル環境生成
RUN ls -lR /home/cross/mkcross;       \
    cd /home/cross/mkcross/workdir ;  \
    ../mkcross-elf.sh;                \
    ls -lR /opt/hos/cross;            \
    rm -fr /home/cross;
