#
# 開発環境コンテナイメージの作成と登録
# -*- coding:utf-8 mode: yaml-mode -*-
# Copyright (C) 1998-2022 by Project HOS
# http://sourceforge.jp/projects/hos/
#
# 事前準備
#  1) GitHubの右上のメニューからSettingsを選択
#  2) 左側のメニュー内のDeveloper settingsを選択
#  3) Personal Access Tokensの項目をクリックする
#  4) 右上のGenerate new tokenボタンを押す
#  5) チェックボックスでwrite packages/read packagesだけを選択
#  6) Generate tokenボタンを押す
#  7) 発行されたPATをテキストファイルに保存
#  8) 本リポジトリのSettingsを開く
#  9) 右上のNew secretをクリック
# 10) Secretの作成画面で, NameをCR_PAT(本ファイル内で参照している名前)に設定し,
#     Valueに, 上記で獲得したPATを貼り付けてAdd secretをクリック.
#
name: Build and publish each cross compiler image for Hyper Operating System
on:
  # 手動実行
  workflow_dispatch:

  push:
    # mainブランチに, scripts/mkcross-elf.shをpushしたら実行
    branches:
      - main
      - github-actions
    paths:
      - 'docker/scripts/mkcross-elf.sh'
      - 'templates/Dockerfiles/Dockerfile.tmpl'
jobs:
  riscv_image:
    # Ubuntu環境のVMでイメージを構築
    runs-on: ubuntu-latest
    env:
      # CPU
      TARGET_CPUS: "riscv32 riscv64"
      # イメージ名
      IMAGE_NAME: crosstool-for-hos-riscv
      # 環境変数/ディレクトリ設定
      - name: Environment variable and work directory
        run: |
          echo "Target CPUS: ${{ env.TARGET_CPUS }}"
          mkdir -p workdir
          cp -a docker/* workdir
          rm -f workdir/Dockerfile
